spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/agro_user_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: sjagrigo2025
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

server:
  port: 8081

jwt:
  secret: "fEUQtX99gAnFEGo7gGZDFPMNZlB7Upqckv2ODONDLL34yXeluushacCkrVJltjhENiCH4zktPXZw1wnkmTU_3Q"
  expiration: 86400000

logging:
  level:
    root: INFO
    com.agroapp.userservice: DEBUG